package br.com.biblia.apps.importador;

import br.com.biblia.enums.LivroEnum;
import lombok.Getter;

public enum AcfLivroEnum {

	GENESIS ("GENESIS", 28),
	EXODO ("EXODO", 29),
	LEVITICO ("LEVITICO", 30),
	NUMEROS ("NUMEROS", 31),
	DEUTERONOMIO ("DEUTERONOMIO", 32),
	JOSUE ("JOSUE", 33),
	JUIZES ("JUIZES", 34),
	RUTE ("RUTE", 35),
	PRIMEIRO_SAMUEL ("PRIMEIRO_SAMUEL", 36),
	SEGUNDO_SAMUEL ("SEGUNDO_SAMUEL", 37),
	PRIMEIRO_REIS ("PRIMEIRO_REIS", 38),
	SEGUNDO_REIS ("SEGUNDO_REIS", 39),
	PRIMEIRO_CRONICAS ("PRIMEIRO_CRONICAS", 40),
	SEGUNDO_CRONICAS ("SEGUNDO_CRONICAS", 41),
	ESDRAS ("ESDRAS", 42),
	NEEMIAS ("NEEMIAS", 43),
	ESTER ("ESTER", 44),
	JO ("JO", 45),
	SALMOS ("SALMOS", 46),
	PROVÉRBIOS ("PROVÉRBIOS", 47),
	ECLESIASTES ("ECLESIASTES", 48),
	CANTARES ("CANTARES", 49),
	ISAÍAS ("ISAÍAS", 50),
	JEREMIAS ("JEREMIAS", 51),
	LAMENTACOES ("LAMENTACOES", 52),
	EZEQUIEL ("EZEQUIEL", 53),
	DANIEL ("DANIEL", 54),
	OSEIAS ("OSEIAS", 55),
	JOEL ("JOEL", 56),
	AMOS ("AMOS", 57),
	OBADIAS ("OBADIAS", 58),
	JONAS ("JONAS", 59),
	MIQUEIAS ("MIQUEIAS", 60),
	NAUM ("NAUM", 61),
	HABACUQUE ("HABACUQUE", 62),
	SOFONIAS ("SOFONIAS", 63),
	AGEU ("AGEU", 64),
	ZACARIAS ("ZACARIAS", 65),
	MALAQUIAS ("MALAQUIAS", 66),
	MATEUS ("MATEUS", 1),
	MARCOS ("MARCOS", 2),
	LUCAS ("LUCAS", 3),
	JOAO ("JOAO", 4),
	ATOS ("ATOS", 5),
	ROMANOS ("ROMANOS", 6),
	PRIMEIRA_CORINTIOS ("PRIMEIRA_CORINTIOS", 7),
	SEGUNDA_CORINTIOS ("SEGUNDA_CORINTIOS", 8),
	GALATAS ("GALATAS", 9),
	EFÉSIOS ("EFÉSIOS", 10),
	FILIPENSES ("FILIPENSES", 11),
	COLOSSENSES ("COLOSSENSES", 12),
	PRIMEIRA_TESSALONICENSES ("PRIMEIRA_TESSALONICENSES", 13),
	SEGUNDA_TESSALONICENSES ("SEGUNDA_TESSALONICENSES", 14),
	PRIMEIRA_TIMOTEO ("PRIMEIRA_TIMOTEO", 15),
	SEGUNDA_TIMOTEO ("SEGUNDA_TIMOTEO", 16),
	TITO ("TITO", 17),
	FILEMOM ("FILEMOM", 18),
	HEBREUS ("HEBREUS", 19),
	TIAGO ("TIAGO", 20),
	PRIMEIRA_PEDRO ("PRIMEIRA_PEDRO", 21),
	SEGUNDA_PEDRO ("SEGUNDA_PEDRO", 22),
	PRIMEIRA_JOAO ("PRIMEIRA_JOAO", 23),
	SEGUNDA_JOAO ("SEGUNDA_JOAO", 24),
	TERCEIRA_JOAO ("TERCEIRA_JOAO", 25),
	JUDAS ("JUDAS", 26),
	APOCALIPSE ("APOCALIPSE", 27);
	
	@Getter
	private LivroEnum livroEnum;
	
	@Getter
	private Integer livroNumber;
	
	private AcfLivroEnum(String enumName, Integer livroNumber) {
		this.livroEnum = LivroEnum.valueOf(enumName);
		this.livroNumber = livroNumber;
	}
	
}
