package br.com.biblia.apps.importador;

import br.com.biblia.enums.LivroEnum;
import lombok.Getter;

public enum BcdnLivroEnum {

	GENESIS ("GENESIS", 1),
	EXODO ("EXODO", 2),
	LEVITICO ("LEVITICO", 3),
	NUMEROS ("NUMEROS", 4),
	DEUTERONOMIO ("DEUTERONOMIO", 5),
	JOSUE ("JOSUE", 6),
	JUIZES ("JUIZES", 7),
	RUTE ("RUTE", 8),
	PRIMEIRO_SAMUEL ("PRIMEIRO_SAMUEL", 9),
	SEGUNDO_SAMUEL ("SEGUNDO_SAMUEL", 10),
	PRIMEIRO_REIS ("PRIMEIRO_REIS", 11),
	SEGUNDO_REIS ("SEGUNDO_REIS", 12),
	PRIMEIRO_CRONICAS ("PRIMEIRO_CRONICAS", 13),
	SEGUNDO_CRONICAS ("SEGUNDO_CRONICAS", 14),
	ESDRAS ("ESDRAS", 15),
	NEEMIAS ("NEEMIAS", 16),
	ESTER ("ESTER", 17),
	JO ("JO", 18),
	SALMOS ("SALMOS", 19),
	PROVÉRBIOS ("PROVÉRBIOS", 20),
	ECLESIASTES ("ECLESIASTES", 21),
	CANTARES ("CANTARES", 22),
	ISAÍAS ("ISAÍAS", 23),
	JEREMIAS ("JEREMIAS", 24),
	LAMENTACOES ("LAMENTACOES", 25),
	EZEQUIEL ("EZEQUIEL", 26),
	DANIEL ("DANIEL", 27),
	OSEIAS ("OSEIAS", 28),
	JOEL ("JOEL", 29),
	AMOS ("AMOS", 30),
	OBADIAS ("OBADIAS", 31),
	JONAS ("JONAS", 32),
	MIQUEIAS ("MIQUEIAS", 33),
	NAUM ("NAUM", 34),
	HABACUQUE ("HABACUQUE", 35),
	SOFONIAS ("SOFONIAS", 36),
	AGEU ("AGEU", 37),
	ZACARIAS ("ZACARIAS", 38),
	MALAQUIAS ("MALAQUIAS", 39),
	MATEUS ("MATEUS", 40),
	MARCOS ("MARCOS", 41),
	LUCAS ("LUCAS", 42),
	JOAO ("JOAO", 43),
	ATOS ("ATOS", 44),
	ROMANOS ("ROMANOS", 45),
	PRIMEIRA_CORINTIOS ("PRIMEIRA_CORINTIOS", 46),
	SEGUNDA_CORINTIOS ("SEGUNDA_CORINTIOS", 47),
	GALATAS ("GALATAS", 48),
	EFÉSIOS ("EFÉSIOS", 49),
	FILIPENSES ("FILIPENSES", 50),
	COLOSSENSES ("COLOSSENSES", 51),
	PRIMEIRA_TESSALONICENSES ("PRIMEIRA_TESSALONICENSES", 52),
	SEGUNDA_TESSALONICENSES ("SEGUNDA_TESSALONICENSES", 53),
	PRIMEIRA_TIMOTEO ("PRIMEIRA_TIMOTEO", 54),
	SEGUNDA_TIMOTEO ("SEGUNDA_TIMOTEO", 55),
	TITO ("TITO", 56),
	FILEMOM ("FILEMOM", 57),
	HEBREUS ("HEBREUS", 58),
	TIAGO ("TIAGO", 59),
	PRIMEIRA_PEDRO ("PRIMEIRA_PEDRO", 60),
	SEGUNDA_PEDRO ("SEGUNDA_PEDRO", 61),
	PRIMEIRA_JOAO ("PRIMEIRA_JOAO", 62),
	SEGUNDA_JOAO ("SEGUNDA_JOAO", 63),
	TERCEIRA_JOAO ("TERCEIRA_JOAO", 64),
	JUDAS ("JUDAS", 65),
	APOCALIPSE ("APOCALIPSE", 66);
	
	@Getter
	private LivroEnum livroEnum;
	
	@Getter
	private Integer livroNumber;
	
	private BcdnLivroEnum(String enumName, Integer livroNumber) {
		this.livroEnum = LivroEnum.valueOf(enumName);
		this.livroNumber = livroNumber;
	}
	
}
